apiVersion: v1
kind: BuildConfig
metadata:
   name: mediabake-build
spec:
   strategy:
     type: Docker
     dockerStrategy:
     from: 
          kind: ImageStreamTag
          name: mediawiki:latest
   source:
       git:
         uri: "https://github.com/hurzelpurzel/mediawiki.git"
         ref: "master"
       contextDir: "config"
       imagePullSecrets:
        - name: 11217608-a422171-pull-secret
   output:
       to:
         kind: DockerImage
         name: docker.io/hurzelpurzel/mediabake:latest
       pushSecret:
         name: "dockerhub"