apiVersion: v1
kind: BuildConfig
metadata:
   name: myimage
spec:
   strategy:
     type: Docker
     dockerStrategy:
       from:
       kind: ImageStreamTag
       name: centos:7
     source:
       type: Git
       git:
         uri: https://github.com/demo/myimage.git
     output:
       to:
         kind: ImageStreamTag
         name: myimage:latest
