apiVersion: v1
kind: BuildConfig
metadata:
   name: mediabake-build
spec:
   strategy:
     type: Docker
     dockerStrategy:
      from:
      kind: "ImageStreamTag"
      name: "mediawiki/mediawiki:latest"
   source:
       git:
         uri: "https://github.com/hurzelpurzel/mediawiki.git"
         ref: "master"
       contextDir: "config"
      
   output:
       to:
         kind: DockerImage
         name: docker.io/hurzelpurzel/mediabake:latest
       pushSecret:
         name: "dockerhub"