apiVersion: v1
kind: BuildConfig
metadata:
   name: mediabake-build
spec:
   strategy:
     type: Docker
     dockerStrategy:
     from: 
          kind: ImageStreamTag
          name: mediawiki:latest
   source:
       git:
         uri: "https://github.com/hurzelpurzel/mediawiki.git"
         ref: "master"
       contextDir: "config"  
   ouput:
       to:
         kind: ImageStreamTag
         name: baked:latest