---
apiVersion: v1
kind: Pod
metadata:
  name: mediawiki
  namespace: mediawiki
  labels: 
    name: mediawiki
spec:
    containers:
      - name: web
        image: "docker.io/hurzelpurzel/mediabake:latest"
        imagePullPolicy: Always
        ports:                              
         - containerPort: 8080
           protocol: TCP
    imagePullSecrets:
      - name: dockerhub
